Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,28 +1,21 @@
 name: Forme
-
 on:
   schedule:
-    # سيتم تشغيل السكربت كل 5 دقائق
     - cron: '1,6,11,16,21,26,31,36,41,46,51,56 * * * *'
-  workflow_dispatch: # يتيح لك تشغيل السكربت يدوياً للتجربة
-
+  workflow_dispatch:
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.9'
-
       - name: Install dependencies
-        run: |
-          pip install requests beautifulsoup4 cloudscraper
-
+        # أضفنا cloudscraper هنا لكي لا يظهر خطأ ModuleNotFoundError
+        run: pip install requests beautifulsoup4 cloudscraper 
       - name: Run Scraper
         env:
           BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
@@ -30,12 +23,10 @@ jobs:
           SAT_USER: ${{ secrets.SAT_USER }}
           SAT_PASS: ${{ secrets.SAT_PASS }}
         run: python Forme.py
-
-      - name: Commit and Push changes
+      - name: Commit and Push
         run: |
           git config --global user.name "GitHub Action"
           git config --global user.email "action@github.com"
-          # إضافة الملفات المحدثة (قاعدة بيانات الشفرات وملف الـ JSON)
-          git add last_keys_list.txt "for me.json" || echo "No files to add"
-          git commit -m "Auto Update: New Keys and JSON" || exit 0
+          git add last_keys_list.txt "for me.json" || echo "Files not found"
+          git commit -m "Update for me.json" || exit 0
           git push
